on:
  push:
    branches:
      - main
jobs:
  deploy-to-front:
    runs-on: ubuntu-latest
    environment: front
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Dependencies
        run: npm install -g cloudron@6.0.0
      - name: Deploy
        run: './.github/workflows/deploy.sh'
        env:
          CLOUDRON_TOKEN: "${{ secrets.ZOROBABEL_GITHUB_ACTION }}"
          CLOUDRON_APP_ID: "${{ secrets.CLOUDRON_APP_ID }}"
          CLOUDRON_FQDN: "${{ secrets.CLOUDRON_FQDN }}"
