on:
  workflow_dispatch:
jobs:
  deploy-to-front-dev:
    runs-on: ubuntu-latest
    environment: front-dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm build
      - name: Cloudron Push to App
        uses: cloudron-io/cloudron-push-to-app@latest
        with:
          CLOUDRON_TOKEN: "${{ secrets.ZOROBABEL_GITHUB_ACTION }}"
          CLOUDRON_APP_ID: "${{ secrets.CLOUDRON_APP_ID }}"
          CLOUDRON_FQDN: "${{ secrets.CLOUDRON_FQDN }}"
          CLOUDRON_PUSH_DESTINATION: "/usr/src/app"
          CLOUDRON_CREATE_APP_BACKUP: "true"
