on:
  workflow_dispatch:
jobs:
  deploy-to-front-dev:
    runs-on: ubuntu-latest
    environment: front-dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm install -g cloudron@6.0.0
      - name: Deploy
        run: './.github/workflows/deploy.sh'
        env:
          CLOUDRON_TOKEN: "${{ secrets.ZOROBABEL_GITHUB_ACTION }}"
          CLOUDRON_APP_ID: "${{ secrets.CLOUDRON_APP_ID }}"
          CLOUDRON_FQDN: "${{ secrets.CLOUDRON_FQDN }}"
